nome = str(input('Qual é seu nome completo? ')).strip()
print('Analisando seu nome...')
print('Seu nome em maiúsculas é: {}'.format(nome.upper()))
print('Seu nome em minúsculas é: {}'.format(nome.lower()))
print('Seu nome inteiro tem o total de {} letras! '.format(len(nome)-nome.count(' ')))
print('Seu nome capitalizado tem {} letras!'.format(nome.capitalize()))
print('Seu nome em título fica {}!'.format(nome.title()))
print('Seu primeiro nome tem {} letras! '.format(nome.find(' ')))
